#!/bin/bash

banner() {
    clear
    printf "
███╗   ███╗ ██████╗ ██████╗ ███████╗██╗  ██╗
████╗ ████║██╔═══██╗██╔══██╗██╔════╝╚██╗██╔╝
██╔████╔██║██║   ██║██║  ██║█████╗   ╚███╔╝ 
██║╚██╔╝██║██║   ██║██║  ██║██╔══╝   ██╔██╗ 
██║ ╚═╝ ██║╚██████╔╝██████╔╝███████╗██╔╝ ██╗
╚═╝     ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝
"
    printf "\e[0m\e[1;33m    Created By GamerModex \e[0m\e[1;31m(\e[0m\e[1;33m Basel Omar \e[0m\e[1;31m)\e[0m\n"
}

menu() {
    printf "\e[0m\n"
    printf "\e[0m\e[1;31m  [\e[0m\e[1;37m01\e[0m\e[1;31m]\e[0m\e[1;33m Start\e[0m\n"
    printf "\e[0m\e[1;31m  [\e[0m\e[1;37m00\e[0m\e[1;31m]\e[0m\e[1;33m Exit\e[0m\n"
    printf "\e[0m\n"
    read -p "\e[1;31m[\e[0m\e[1;37m~\e[0m\e[1;31m]\e[0m\e[1;92m Select An Option \e[0m\e[1;96m: \e[0m\e[1;93m" option

    if [[ $option == 1 || $option == 01 ]]; then
        sleep 5
        myipaddr
    elif [[ $option == 0 || $option == 00 ]]; then
        sleep 1
        printf "\e[0m\n"
        printf "\e[0m\n"
        exit 1
    else
        printf " \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
        sleep 1
        banner
        menu
    fi
}

myipaddr() {
    myipaddripapico=$(curl -s "https://ipapi.co/json" -L)
    myipaddripapicom=$(curl -s "http://ip-api.com/json/" -L)
    myip=$(echo $myipaddripapico | grep -Po '(?<="ip":")[^"]*')
    mycity=$(echo $myipaddripapico | grep -Po '(?<="city":")[^"]*')
    myregion=$(echo $myipaddripapico | grep -Po '(?<="region":")[^"]*')
    mycountry=$(echo $myipaddripapico | grep -Po '(?<="country_name":")[^"]*')
    mylat=$(echo $myipaddripapicom | grep -Po '(?<="lat":)[^,]*')
    mylon=$(echo $myipaddripapicom | grep -Po '(?<="lon":')[^,]*')
    mytime=$(echo $myipaddripapicom | grep -Po '(?<="timezone":")[^"]*')
    mypostal=$(echo $myipaddripapicom | grep -Po '(?<="zip":")[^"]*')
    myisp=$(echo $myipaddripapico | grep -Po '(?<="org":")[^"]*')
    myasn=$(echo $myipaddripapico | grep -Po '(?<="asn":")[^"]*')
    mycountrycode=$(echo $myipaddripapico | grep -Po '(?<="country_code":")[^"]*')
    mycurrency=$(echo $myipaddripapico | grep -Po '(?<="currency":")[^"]*')
    mylanguage=$(echo $myipaddripapico | grep -Po '(?<="languages":")[^"]*')
    mycalling=$(echo $myipaddripapico | grep -Po '(?<="country_calling_code":")[^"]*')

    banner
    printf "\e[0m\n"
    printf "\e[0m\n"
    printf "  \e[0m\e[1;93m  Ip Address    \e[0m\e[1;96m:\e[0m\e[1;92m   $myip\e[0m\n"
    printf "  \e[0m\e[1;93m  City          \e[0m\e[1;96m:\e[0m\e[1;92m   $mycity\e[0m\n"
    printf "  \e[0m\e[1;93m  Region        \e[0m\e[1;96m:\e[0m\e[1;92m   $myregion\e[0m\n"
    printf "  \e[0m\e[1;93m  Country       \e[0m\e[1;96m:\e[0m\e[1;92m   $mycountry\e[0m\n"
    printf "\e[0m\n"
    printf "  \e[0m\e[1;93m  Latitude      \e[0m\e[1;96m:\e[0m\e[1;92m    $mylat\e[0m\n"
    printf "  \e[0m\e[1;93m  Longitude     \e[0m\e[1;96m:\e[0m\e[1;92m    $mylon\e[0m\n"
    printf "  \e[0m\e[1;93m  Time Zone     \e[0m\e[1;96m:\e[0m\e[1;92m    $mytime\e[0m\n"
    printf "  \e[0m\e[1;93m  Postal Code   \e[0m\e[1;96m:\e[0m\e[1;92m    $mypostal\e[0m\n"
    printf "\e[0m\n"
    printf "  \e[0m\e[1;93m  ISP           \e[0m\e[1;96m:\e[0m\e[1;92m   $myisp\e[0m\n"
    printf "  \e[0m\e[1;93m  ASN           \e[0m\e[1;96m:\e[0m\e[1;92m   $myasn\e[0m\n"
    printf "\e[0m\n"
    printf "  \e[0m\e[1;93m  Country Code  \e[0m\e[1;96m:\e[0m\e[1;92m   $mycountrycode\e[0m\n"
    printf "  \e[0m\e[1;93m  Currency      \e[0m\e[1;96m:\e[0m\e[1;92m   $mycurrency\e[0m\n"
    printf "  \e[0m\e[1;93m  Languages     \e[0m\e[1;96m:\e[0m\e[1;92m   $mylanguage\e[0m\n"
    printf "  \e[0m\e[1;93m  Calling Code  \e[0m\e[1;96m:\e[0m\e[1;92m   $mycalling\e[0m\n"
    printf "\e[0m\n"
    printf "  \e[0m\e[1;93m  GOOGLE Maps   \e[0m\e[1;96m:\e[0m\e[1;94m  https://maps.google.com/?q=$mylat,$mylon\e[0m\n"
    sleep 5
    printf "\e[0m\n"
    printf "  \e[0m\e[1;91m[\e[0m\e[1;97m01\e[0m\e[1;91m]\e[0m\e[1;93m Return To Main Menu\e[0m\n"
    printf "  \e[0m\e[1;91m[\e[0m\e[1;97m02\e[0m\e[1;91m]\e[0m\e[1;93m Exit\e[0m\n"
read -p $'  \e[1;31m>>\e[0m\e[1;96m  \en' mainorexit1

if [[ $mainorexit1 == 1 || $mainorexit1 == 01 ]]; then
banner
menu
elif [[ $mainorexit1 == 2 || $mainorexit1 == 02 ]]; then
printf "\e[0m\n"
printf "\e[0m\n"
exit 1

else
printf " \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
sleep 1
banner
menu
fi

}







banner
menu
